### ISSUE TITLE
hw2: флаги компиляции

### ISSUE THREAD

**Issue by victor-yacovlev** [demist/pl.task2#1]
При сборке возникает ошибка:
```
luamodule.c:25:5: error: ISO C90 forbids mixed declarations and code
[-Werror=declaration-after-statement]
     lua_State *L;
  ```
Что вполне логично - в ISO C90 такая конструкция запрещена, а gcc по умолчанию воспринимает код как ISO C90. Возможность объявления переменных вперемешку с кодом появилась только в стандарте C99: `-std=c99`.

**Comment by demist** [comment]
Добрый день!

На моей машине вызов компилятора выглядит так:
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -I/usr/include/lua5.2/ -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.4m -c luamodule.c -o build/temp.linux-x86_64-3.4/luamodule.o
Версия компилятора 4.9.2

Ошибка не наблюдается, хотя флаг -std=c99 отсутствует.  
Поэтому я, видимо, не придал значения. 

Добавлю это в build.sh

**Comment by demist** [comment]
Добрый день!

На моей машине вызов компилятора выглядит так:
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall
-Wstrict-prototypes -I/usr/include/lua5.2/ -D_FORTIFY_SOURCE=2 -fPIC
-I/usr/include/python3.4m -c luamodule.c -o
build/temp.linux-x86_64-3.4/luamodule.o
Версия компилятора 4.9.2

Ошибка не наблюдается, хотя флаг -std=c99 отсутствует.
Поэтому я, видимо, не придал значения.


С уважением,
Старичков Никита
mail@starichkov.com
stan@1c.ru
+7-999-995-29-24

27 октября 2016 г., 14:17 пользователь Victor Yacovlev <
notifications@github.com> написал:
